name: Create Github Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

env:
  PYTHON_VERSION: '3.12'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Composite to install poetry
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          install-dependencies: false

      - name: Extract version of tag
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted version: ${VERSION}"

      - name: Determine pre-release
        run: |
          if [[ "$VERSION" == *"-rc"* ]]; then
            echo "IS_PRE_RELEASE=true" >> GITHUB_ENV
          else
            echo "IS_PRE_RELEASE=false" >> GITHUB_ENV
          fi

      - name: Build package with new version
        run: |
          VERSION="$VERSION"
          poetry build
          echo "Python package built with version $VERSION"
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Built artifacts >> $GTIHUB_STEP_SUMMARY"
          ls -lh dist/ >> $GITHUB_STEP_SUMMARY

      - name: Verify package
        run: |
          VERSION="$VERSION"
          if ls dist/*.whl 1> /dev/null 2>&1; then
            echo "Build successful"
            echo "Build files:"
            ls -lh dist
          else
            echo "No wheels found"
            exit 1
          fi

      - name: Create github release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release created after merge."
          draft: false
          prerelease: $IS_PRE_RELEASE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
